# Generated by Django 4.0.1 on 2022-02-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_is_post_blog_blog_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_user',
            new_name='blog_author',
        ),
    ]
