# Generated by Django 4.0.1 on 2022-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_add_pincode_patient_add_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_no',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_higest',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specilization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='add_Pincode',
            field=models.IntegerField(blank=True, default=831001),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='add_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='add_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='add_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='asset/profile-pic/default.png', upload_to='asset/profile-pic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='add_Pincode',
            field=models.IntegerField(blank=True, default=831001),
        ),
        migrations.AlterField(
            model_name='patient',
            name='add_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='add_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='add_state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
