# Generated by Django 4.0.1 on 2022-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_about_doctor_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
