# Generated by Django 4.0.1 on 2022-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctor_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='asset/profile-pic/default.png', upload_to='asset/profile-pic'),
        ),
    ]
