# Generated by Django 4.0.1 on 2022-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='add_Pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='add_Pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
