# Generated by Django 4.0.1 on 2022-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_add_pincode_alter_patient_add_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='add_Pincode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
