# Generated by Django 4.0.1 on 2022-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_patient_add_pincode_alter_patient_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='add_Pincode',
            field=models.IntegerField(default=831001),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_no',
            field=models.IntegerField(default=9087654321),
        ),
    ]
