# Generated by Django 4.0.1 on 2022-02-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctor_first_name_alter_doctor_last_name_and_more'),
        ('hospital', '0008_alter_doctor_add_pincode_alter_doctor_phone_no'),
    ]

    operations = [
    ]
